### ISSUE TITLE
Scope injection.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#10]
Sometimes it's real handy to have pre-injected variables in all define().
I think it can be implemented through filter and some new run-level.
And then when scopes fired inject all variables of filter in this scope.
What do you think?

I'am talking about something like

```php
// Config
Filter::register("app.helpers", function() {
   $scope = $this->scope();
   
   $helper = new \My\Namespace\Helper();
   $scope->inject($helper);
});


// Spec
describe("My Spec", function() {
    before(function() {
        $this->helper->do_some_action();
    });
});
```

**Comment by jails** [comment]
Imo it should be easily done using the following syntax:
```
Filter::register('registering.globals', function($chain) {
    $root = $this->suite();
    $root->global = 'hello';
    return $chain->next();
});

Filter::apply($this, 'run', 'registering.globals');
```

**Comment by m1ome** [comment]
I think i'll add this do documentation if you don't mind.

**Comment by jails** [comment]
No problem !
