### ISSUE TITLE
Type hinting is broken

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#100]
Somewhere since `1.1.8` version `expect()` function became a global wrapper function without any docs (`src/init.php:65`) and so type hinting (in phpStorm) that worked properly before now is broken and so autocomplete too.
Is it possible to fix that?

**Comment by jails** [comment]
Good catch, yeah looks like I mistakenly removed the related doc block. Fixed in https://github.com/crysalead/kahlan/commit/6e0aed86a2c38cbb2336c5cef813e89a3d289cad
