### ISSUE TITLE
help function and coverage docs

### ISSUE THREAD

**Issue by LostKobrakai** [crysalead/kahlan#101]
I just struggled over an hour to get code coverage to run, as i always got this error: 
`Uncaught exception 'Exception' with message 'Unexisting path 'src'.' in /tmp/kahlan/var/www/live/site/vendor/crysalead/dir/src/Dir.php:91`

After looking at the erroring file and digging this repo I eventually found the help output of the cli, which listed the src argument, which I needed to change. It would be really nice if you could make the exception a bit more descriptive, like "Couldn't find the supplied root folder 'src'." and maybe enhance the docs around the coverage function with a note, that the src argument must be correctly set.
 
Additionally, the help functionality does not work for me in the console. `kahlan --help` does simply output the same as without argument.

**Comment by jails** [comment]
Indeed by default sources are checked over `'src'`, I'll add a note in the documentation.

By the way I'm not sure to get what's wrong with `kahlan --help`, the display seems correct for me:
![screenshot - 11112015 - 18 27 15](https://cloud.githubusercontent.com/assets/1306941/11097878/dc37f2ec-88a1-11e5-9888-7e76b2a02491.png)

**Comment by jails** [comment]
Note added in https://github.com/crysalead/kahlan/commit/e66596d2ba5a57c727afd75de7ac06d8532e643d

**Comment by LostKobrakai** [comment]
I think I got the culpit why the help content isn't showing up. I've some changed default arguments in my kahlan-config.php:
```php
<?php
/**
 * @var kahlan\cli\Args $args
 */
$args = $this->args();
$args->argument('reporter', ['default' => 'verbose']);
$args->argument('src', ['default' => 'domain']);
$args->argument('coverage', ['default' => 3]);
```
So maybe these can be ignored if the help is requested.

**Comment by jails** [comment]
Ah yeah fair enough, fixed in https://github.com/crysalead/kahlan/commit/dbd66b8172d09a4e69d692955f17df4bb9c82573
