### ISSUE TITLE
Stub not working

### ISSUE THREAD

**Issue by LostKobrakai** [crysalead/kahlan#102]
Somehow the following stub for an internal class of my cms doesn't work like expected. Normally I would bootstrap the cms with the `include_once`, so all internals are correctly loaded and set up. But even by using a custom autoloader, like described in the docs, and creating new instances of those classes the method isn't stubed.
Am I missing something here?

```php
use kahlan\plugin\Stub;

// include_once "../index.php";

describe("Test Stubing", function() {

	it("should be saveable", function () {
		$page = new NullPage();
		$instance = new Pages();
		$reason = '';
		Stub::on($instance)->method('isSaveable')->andReturn(true);
		expect($instance->isSaveable($page, $reason))->toBe(true);
		var_dump($reason);
	});

});
```

```
string(39) "Pages of type NullPage are not saveable"
  ✘ it should be saveable
    expect->toBe() failed in `/spec/TrainerInvoices/TrainerInvoicesSpec.php` line 20
```

in kahlan-config.php
```php
Filter::register('mycustom.namespaces', function($chain) {

	$this->autoloader()->addPsr4('', __DIR__ . '../wire/core');
	return $chain->next();

});

Filter::apply($this, 'namespaces', 'mycustom.namespaces');
```

Edit:
I've checked another class in my custom namespace and it got stubed without problem.

**Comment by jails** [comment]
Patching only work inside classes loaded by Composer. For example if you try to Stub or Monkey patch something which has been loaded by a custom loader, it won't work. However if your project structure is PSR-0 compatible, disabling the custom autoloader and adding something like you did:
```php
Filter::register('mycustom.namespaces', function($chain) {

	$this->autoloader()->addPsr4('', __DIR__ . '../wire/core');
	return $chain->next();

});

Filter::apply($this, 'namespaces', 'mycustom.namespaces');
```
It should work out of the box.

If you're still stuck, feel free to update your https://github.com/LostKobrakai/kahlan-debug-repo repo with your example so I can take a look.

**Comment by LostKobrakai** [comment]
I got it, thanks for your help and patience. The classes where still loaded because I had the same include statement in another spec file and not because of the autoloader correctly loading the files. I'll close this, but I've still one question: 
If the autoloader does correctly detect those classes, can I still stub instances, which where instanciated somewhere in the cms, which (also) loaded the classes by a custom autoloader? All the classnames and paths and so on should be the same.

**Comment by jails** [comment]
By default you'll be able to stub all classes loaded by the composer autoloader, i.e the ones defined in your `composer.json` file.
However if all classes your project are not managed by composer (not recommanded imo), you'll still be able to manually add some PSR-0/PSR-4 namespaces or class map through the kahlan config file.
Anyhow the easy way is to disable/remove all custom autoloaders and let composer do all the autoloading. All others situations will need to be solved on a case-by-case basis but may lead to some unnecessary extra complexity.
