### ISSUE TITLE
Installing as global composer package and running the app does not look in right folder

### ISSUE THREAD

**Issue by crissi** [crysalead/kahlan#104]
Installing kahlan with "composer global require --dev crysalead/kahlan"

and then cd'ing into a project from the console and running kahlan will produce this error:

Fatal error: Uncaught exception 'Exception' with message 'Unexisting path `spec`.' in C:\Users\crissi\AppData\Local\Temp\kahlan\C\Users\crissi\AppData\Roaming\Composer\vendor\crysalead\dir\src\Dir.php:92

Even though the project has a spec folder.

**Comment by jails** [comment]
Good catch :+1:, should work with the last version.
Fixed in https://github.com/crysalead/kahlan/commit/2c461bd6c3c89be547748d4060b9412b974157ff

**Comment by jails** [comment]
Btw this fix https://github.com/crysalead/kahlan/commit/db203f76f05c9da40f497ce691e996cfdac894c6 would make the binary script more flexible, so upgrading up to 1.2.10 is recommended.
