### ISSUE TITLE
Matcher `->toBeOneOf()` feature request

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#106]
How about new handy matcher with following semantics
```php
expect(1)->toBeOneOf([1, 2, 3]);  // ok
expect(0)->toBeOneOf([1, 2, 3]);  // not ok
```
instead of
```php
expect(in_array(1, [1, 2, 3], true))->toBe(true);
```
?

**Comment by tyranron** [comment]
Hmm...additionally
```php
expect(1)->toEqualOneOf([1, 2, 3]);
```
instead of
```php
expect(in_array(1, [1, 2, 3]))->toBe(true);
```
for more conveniency?

**Comment by pluxain** [comment]
Maybe the already existing `toContain()` matcher would suit your needs ?

In the [documentation](http://kahlan.readthedocs.org/en/latest/matchers/#classic) you can see an example like :

    expect([1, 2, 3])->toContain(1);

**Comment by tyranron** [comment]
Yeap, sure. For the code it's totally same.
But for human these situations are slightly different:
* `expect($actual = [1, 2, 3])->toContain($expected = 1);` means "we expect array $actual (which is tested) to contain expected value $value"
* `expect($actual = 1)->toBeOneOf($expected = [1, 2, 3]);` means "we expect value $actual (which is tested) to be one of values in set $expected (given as array)"

This feature request is not about lack of `Kahlan` matchers abilities, it's about more syntax sugar for better readability and understanding by humans.

**Comment by pluxain** [comment]
I understand what you say, but readability is also about context :

```php
it('sounds readable enough to me', function() {
    $actual = 1;
    $expected = [1, 2, 3];
    expect($expected)->toContain($actual);
});
```

Isn't it ?

**Comment by jails** [comment]
@tyranron I personnaly didn't needed it often so I'll leave this issue opened to check if it's a recurrent need.

**Comment by tyranron** [comment]
@pluxain 
> Anyway making a custom matcher to achieve what you want might not be too difficult :)
Sure. It's only a proposal to have it by default.

@jails thank you.

**Comment by jails** [comment]
I'm closing this since it's probably better to set up a custom matcher when the "scope" of a matcher is limited to keep a small API.

**Comment by tyranron** [comment]
Okay =(

**Comment by Kaijiro** [comment]
It may be a little late, but I encountered a case which is not so uncommon ...

Ex : you retrieve an entity via an API and this entity may have a field that must be one of the value of a known array. For a real case, I retrieve promotions from an API inside which there is a field named "promotion_type". This field can be only be "PERCENTAGE" or "PRICE".

Given this situation, I think every case where we get an entity which have this type of field which is not driven by an enum can have use of this type of matcher.
