### ISSUE TITLE
toThrow() matcher to just check Exception type even if $actual has a code

### ISSUE THREAD

**Issue by pluxain** [crysalead/kahlan#107]
Hi,

I don't know exactly if this is an issue, but I have some problems with the `ToThrow` matcher. In the documentation it is presented as is 
```php
it("passes if $closure throws the $expected exception", function() {

    $closure = function() {
        // place the code that you expect to throw an exception in a closure, like so
        throw new RuntimeException('exception message');
    };
    expect($closure)->toThrow();
    expect($closure)->toThrow(new RuntimeException());
    expect($closure)->toThrow(new RuntimeException('exception message'));

});
```
which led me to think that in the second expectation `expect($closure)->toThrow(new RuntimeException());`, only the exception type was checked.

But if the exception thrown has a code then it fails
```php
it('fails if the exception thrown has a code <> 0', function() {
    $closure = function() {
        throw new RuntimeException('dummy message', 1234);
    };
    expect($closure)->toThrow(new RuntimeException());
});
```
This fails as it seems to compare the message and the code of the RuntimeException thrown by the closure.
``` 
✘ it fails if the exception thrown has a code <> 0
      expect->toThrow() failed in `/spec/suite/MySpec.php` line 131
      
      actual:
        (object) `PDOException` Code(1234) with message "dummy message" in /spec/suite/MySpec.php
      expected:
        (object) `PDOException` Code(0) with no message in /spec/suite/MySpec.php
```

This can be problematic when testing code which will trigger PDOException that have very different codes and complicated messages.

**Comment by pluxain** [comment]
I've seen the ToThrowSpec of kahlan and used the specs like
```php
expect($closure)->toThrow(null, 1234);
```
And then it passes. But against real code which trigger a PDOException, it fails... I don't understand.

**Comment by jails** [comment]
Can you please share your complete spec and your expectations so I can take a look at it ?

**Comment by pluxain** [comment]
Sure. I simplified it to avoid too much noise...
In this spec, `person()` is a helper function which insert a Person in database using my little ORM. The database has a unique constraint on the `email` field on the `persons` table.

```php
        it('cannot have duplicate email', function() {
            $closure = function() {
                $email = faker()->email;
                person(['email' => $email]);
                person(['email' => $email]);
            };
            expect($closure)->toThrow(new \PDOException(null, 23505));
        });
```

Basically the closure will throw something like 
```
`PDOException` Code(23505) with message "SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"persons_uq\"
DETAIL:  Key (lower(email::text))=(ebayer@gmail.com) already exists." in /private/var/folders/2m/sth_k13d5d5_z13lf42796kh0000gn/T/kahlan/Projects/php/MyProject/Yam/Models/CoreModel.php:313
```

**Comment by jails** [comment]
The following seems to work for me:
```php
it("catches PDOException", function() {
    $closure = function() {
        throw new  \PDOException("duplicate key value violates unique constraint etc...", 23505);
    };
    expect($closure)->toThrow(new \PDOException(null, 23505));
});
```
Are you sure of your PDOException code value ?

**Comment by pluxain** [comment]
Yes I tried what you did and it indeed worked. But in the real situation this does not work.

It does not seem to be a kahlan related problem. I will check further the PDOException code value  and let you know. I naively used the report text to define the code to expect.

Thanks anyway.

**Comment by pluxain** [comment]
I checked the PDOException thrown by my code and its code value is ok.

**Comment by jails** [comment]
I can't really help, you will need to find out which one is failing between `sameCode` && `sameMessage` and why right from the vendor source:
https://github.com/crysalead/kahlan/blob/master/src/Matcher/ToThrow.php#L89-L90

**Comment by pluxain** [comment]
Sure you couldn't help, the problem was in my code obviously !

I fixed the problem by modifying my code.

Basically the `PDOStatement->execute()` was throwing an exception. This was the problem I guess as by catching it and throwing a new proper PDOException with the message and code set properly, kahlan expectation worked.

Thanks for your help.

**Comment by jails** [comment]
:+1:
