### ISSUE TITLE
Invalid characters after beep

### ISSUE THREAD

**Issue by LostKobrakai** [crysalead/kahlan#109]
I just installed netatalk on a vm of mine and since then kahlan is beeping when started and then it does output lot's of invalid chars like so `��}	�`. This is before even the header is outputed. Is there any way to debug this, as there's no error message, just the beep.

**Comment by LostKobrakai** [comment]
Just to note, kahlan is still running the tests, it's just the console filled with those questionmarks.

**Comment by jails** [comment]
Does adding `--no-colors` solve this issue ?

**Comment by LostKobrakai** [comment]
Nope. Did work with the colors before as well.

**Comment by jails** [comment]
Can you gist a full output with `--no-colors` enabled ?

**Comment by LostKobrakai** [comment]
https://gist.github.com/LostKobrakai/42e951e58d8557d18901

**Comment by jails** [comment]
Hmm doesn't sounds like a Kahlan issue.
It looks like more another process runned in the background which generates some console ouput conflicting with Kahlan's one.

**Comment by LostKobrakai** [comment]
I'd did already suspect that, but I cannot guess anything that would suddenly run before kahlan called by it's own binary.

**Comment by jails** [comment]
If it's really realated to kahlan, I don't see any other alternative that adding some breakpoints (using `exit()` for example) at each steps of https://github.com/crysalead/kahlan/blob/master/src/Cli/Kahlan.php#L341 until reaching the output responsible of that.

**Comment by LostKobrakai** [comment]
Ok, got the issue.

```
array(6) {
  [0]=>
  string(20) "spec/FactorySpec.php"
  [1]=>
  string(17) "spec/TestSpec.php"
  [2]=>
  string(23) "spec/FunctionalSpec.php"
  [3]=>
  string(33) "spec/.AppleDouble/FactorySpec.php"
  [4]=>
  string(30) "spec/.AppleDouble/TestSpec.php"
  [5]=>
  string(36) "spec/.AppleDouble/FunctionalSpec.php"
}
```
What do you think about excluding such dot-folders by default? I doubt someone would expect files in them to run.

**Comment by LostKobrakai** [comment]
Excluding `*/.*` in Kahlan::_load() seems to do that.

**Comment by jails** [comment]
I'm not sure this filter will for subdirs.

**Comment by LostKobrakai** [comment]
This seems to work for me. It should stop the iterator as soon as it hits a .name folder.

**Comment by jails** [comment]
Indeed, so yeah fell free to open a PR so it can be the default behavior. I'll check this later to see if I need to make it configurable or not.

**Comment by LostKobrakai** [comment]
Added the PR. Thank for your quick help again :)
