### ISSUE TITLE
Before and BeforeEach.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#11]
How can i control a chain which of this call first?
If there is some predicted flow i think it needed to be documented.

**Comment by jails** [comment]
They are supposed to follow scopes like in Jasmine. `before` / `beforeEach` are executed depending on their position in the scoper. For example:
```php
describe(function() {
    before(function() {
       //B1
    });
    describe(function() {
        before(function() {
           //B2
        });
        beforeEach(function() {
           //b1
        });
        it("runs a spec", function() {
           //i1
        });
        it("runs a spec", function() {
           //i2
        });
        afterEach(function() {
           //a1
        });
        after(function() {
           //A2
        });
    });
    after(function() {
       //A1
    });
});
```

will give the following execution:
B1 - B2 - b1 - i1 - a1 - b1 - i2 - a1 - A2 - A1

**Comment by m1ome** [comment]
Ok, i will also add this into doc.
