### ISSUE TITLE
expect()->toReceive() fails when used on Phalcon's \Phalcon\Forms\Form class if the fully registered name is declared at the top with "use" syntax

### ISSUE THREAD

**Issue by ybenzine** [crysalead/kahlan#112]
Pardon the long-ish title but this issue is a bit tricky to summarize. Moreover, I want to point out that our developers are heavily suspecting that the issue is with [Phalcon](https://docs.phalconphp.com/en/latest/index.html) and not Kahlan. Nonetheless, it could prove useful to someone who is having similar issues when using a combination of Kahlan and Phalcon.

The Phalcon framework offers a [`Form`](https://docs.phalconphp.com/en/latest/api/Phalcon_Forms_Form.html) component to build forms using an object-oriented interface. Here is a very simple example:

```php
// Filename: AccountForm.php
namespace My\Namespace\User\Forms;

use Phalcon\Mvc\Url;
use Phalcon\Forms\Element\Text;
use Phalcon\Forms\Element\Submit;
// etc ...

class AccountForm extends \Phalcon\Forms\Form
{
    public function initialize()
    {
        $this->build();
    }

/** Some methods removed for readability */

    public function getEmailField()
    {
        $email = new Text('email', [
            'placeholder' => 'Email'
        ]);
        $email->addValidators($this->getEmailValidators());
        return $email;
    }

    public function getSubmitButton()
    {
        $button = new Submit('Validate', [
            'id' => 'account_submit'
        ]);

        return $button;
    }

    public function build()
    {
        $this->setAction($this->getActionUrl());
        $this->add($this->getEmailField());
        $this->add($this->getSubmitButton());
    }
}
```

And this is a sample spec for this form:

```php
// Filename: AccountFormSpec.php
namespace My\Namespace\User\Forms;

use kahlan\plugin\Stub;
use Phalcon\Forms\Element\Submit;
// etc ...

describe('AccountForm', function () {
    beforeEach(function () {
        $this->form = new AccountForm();
    });

/** Contexts removed for readability */

    context('submit button', function () {
        describe('->build()', function () {
            it('adds submit button', function () {
                $submit_button = Stub::create(['implements' => [ElementInterface::class]]);

                Stub::on($this->form)
                    ->method('getSubmitButton')
                    ->andReturn($submit_button);

                expect($this->form)
                    ->toReceive('add')
                    ->with($submit_button);

                $this->form->build();
            });
        });
    });
});
```
As shown above, the test passes with no problems:
```
AccountForm
  submit button
    ->build()
      ✔ it adds submit button
```

However, if you were to make a change in `AccountForm.php` consisting of moving the fully qualified name of the extended class:
```php
class AccountForm extends \Phalcon\Forms\Form
```
To be declared before the class:
```php
use \Phalcon\Forms\Form;

class AccountForm extends Form
```
Then Kahlan returns this:
```
  submit button
    ->build()
      ✘ it adds submit button
        expect->toReceive() failed in `/spec/Forms/AccountFormSpec.php` line 102

        actual received:
          (array) [
              0 => "build",
              1 => "getActionUrl",
              2 => "getEmailField",
              3 => "getEmailValidators",
              4 => "getSubmitButton"
          ]
        expected:
          (string) "add"
```

My colleague Eugene has [an open ticket on the phalcon/cphalcon repository](https://github.com/phalcon/cphalcon/issues/11329) pointing out this issue which has yet to be addressed. But I figured it might be worth pointing this out here as well.

**Comment by jails** [comment]
Does adding the `add()` function like in the following:

```php
class AccountForm extends {
    /* ... */
    public function add (\Phalcon\Forms\ElementInterface $element) {
        parent::add($element);
    }
   /* ... */
}
```
inside the `AccountForm` class makes the spec pass in the second example ?

**Comment by ybenzine** [comment]
@jails: no, it does not. I tried this in both the first and second examples and it does not affect the outcome either way.

It seems to be specific to `Phalcon\Forms\Form` which is why we are more suspicious of Phalcon than Kahlan.

**Comment by jails** [comment]
Is it possible to have all this example bundled into a repo so i can fork it and make some tests locally ?

**Comment by ybenzine** [comment]
Actually, I apologize: it does pass when overloading: 
```php
public function add (\Phalcon\Forms\ElementInterface $element, $postion = NULL, $type = NULL)
{
    parent::add($element, $postion, $type);
}

```
I saw an error and read it too quickly but it was another error due to another method I had to overload: `setAction($action)`. All tests pass when following this logic (though it does feel a bit unnecessary).

I will try to put together a small repo for you to test out if you'd like.

**Comment by jails** [comment]
So I think it's a Kahlan issue.
I guess you setted up a layer patcher like the following:

```php
Filter::register('api.patchers', function($chain) {
    if (!$interceptor = Interceptor::instance()) {
        return;
    }
    $patchers = $interceptor->patchers();
    $patchers->add('layer', new Layer([
        'override' => [
            'Phalcon\Forms\Form'
        ]
    ]));

    return $chain->next();
});

And the fact that `Phalcon` is a C extension some PHP Layers are required. So at some point the JIT parser failed to reconcile  `Phalcon\Forms\Form` & `Form` when the `use` statement is used.

**Comment by ybenzine** [comment]
You're correct about the set up, it's almost exactly like that. The only difference is that we also override `Phalcon\Mvc\Model`.

This is only annoying in the sense that ideally, we would love to follow PSR standards. But since it's relatively easy to get around this issue, we can live with it for now. It could be worth documenting for other users of Kahlan and Phalcon, though.

**Comment by jails** [comment]
It should be fixed in the `dev` branch, https://github.com/crysalead/kahlan/commit/419ef2a58e75c6c20c34e2390d864929f1f1fb8d

Feel free to test it so I can tag a new version if it's ok.

**Comment by jails** [comment]
I'm assuming it has been fixed, feel free to reopen otherwise.
