### ISSUE TITLE
Kahlan site.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#12]
Some projects like [Peridot](http://peridot-php.github.io/) have they own good-looking site, and it's kinda helpful to have such one, a lots of new people may just use Peridot, because of their better documentation and good-looking lifted-up site. What do you think, about this?

**Comment by jails** [comment]
If I have some free time, I would prefer to spend some time working on libraries like Kahlan. If people use libraries because of their popularity, I'm fine with that. Anyhow, these people are not the ones who are going to contribute to open source projets.

**Comment by m1ome** [comment]
You can create a repo for it, and i can try to contribute some start things to site. It needs to be kinda simple and informative. Some thing in documentations is just missing, they are only in your head, it need to be more structured, IMHO.

**Comment by jails** [comment]
Which part of the documentation you don't like or is missing ?

**Comment by m1ome** [comment]
1. Nothing about method chaining.
2. Nothing about integration with popular frameworks.
3. Examples of code-coverage config.
4. Example of implementing own reporter.
5. More about function stubbing (function stub must have all non-stub function arguments passed)

**Comment by jails** [comment]
I'm closing it for now since you did almost all the work :+1:
