### ISSUE TITLE
How to mock a php file_get_contents function

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#127]
@jails @m1ome
 I have a function which does file_get_contents of a jsonn file

```
$json_data = file_get_contents("abc.json");
$json_object = json_decode($json_data,true);
```
How can I mock it so that it rather getting contents from **abc.json** it access the sample file provided ie 
somewhat like **sample.json**

**Comment by jails** [comment]
Like in the [documentation](http://kahlan.readthedocs.org/en/latest/monkey-patching/)

**Comment by shivshankarsomu** [comment]
As per my knowlegde
Monkey patching for user-defined functions not for PHP inbuilt functions.

**Comment by jails** [comment]
It's in the documentation:

> Monkey Patching allows replacement of core functions and classes that can't be stubbed, for example time(), DateTime or MongoId for example.
