### ISSUE TITLE
Weird characters in second describe in windows

### ISSUE THREAD

**Issue by flip111** [crysalead/kahlan#128]
When i have an `it` in a `describe` and kahlan detects an error, on windows the line will start with `Ô£ÿ` followed by the normal `it`-message

**Comment by jails** [comment]
I'm not using Windows, so either create a repo with the issue so I can clone it and test it locally, or you'll need to investigate on this issue by yourself.

**Comment by flip111** [comment]
You want to test it locally to see if the problem also occurs on other OS than windows?

**Comment by jails** [comment]
I can't help without a real example.

**Comment by flip111** [comment]
If you clone this repo https://github.com/crysalead/text change [this line](https://github.com/crysalead/text/blob/master/spec/Suite/TextSpec.php#L19) to `$expected = 'Obi-Wan is awesome.EXTRA';` you will get as output

![image](https://cloud.githubusercontent.com/assets/2244480/14347545/f8d1fad0-fcb7-11e5-85b5-5ef3feb98eaa.png)

`Ô£ÿ ` is appended to `it inserts scalar variables in a string`

**Comment by jails** [comment]
Does `./bin/kahlan --no-colors` give the same result ?

**Comment by flip111** [comment]
yes

**Comment by jails** [comment]
Ok so I think the mark symbol ✘  (i.e. U+2717 or U+2718) is not supported by your console.

**Comment by flip111** [comment]
```php
if (DIRECTORY_SEPERATOR = ''\\) {
	exec('chcp 65001');
}
```

This is a possible fix, from: http://stackoverflow.com/a/388500 otherwise maybe not use that character at all when on windows.

By the way, for me this issue is extremely low priority, i just thought i would report it ^^

**Comment by jails** [comment]
I think it's not a kahlan issue but an environment based issue.
You should add `chcp 65001` in your `.bashrc` or equivalent instead.

**Comment by m1ome** [comment]
It's a Windows-based feature and idk if it affects all current versions.

**Comment by m1ome** [comment]
@flip111 it looks pretty hacky. Normal fix is to check that's we are at Windows Platform and write just "v"

**Comment by jails** [comment]
Imo the fix is to let window's user to correctly configure their cygwin (or whatever) terminal in UTF-8
