### ISSUE TITLE
MOCK REDIS CACHE SERVICE

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#129]
@jails @m1ome

I have used redis cache service in my application and I have a lot of PHP PHALCON functions which either save into redis cache or either retrieves from **REDIS CACHE**.

Can u please help me how can I redis cache service so that my tests donot interact live data rather than dummy data provided by me.

**Comment by m1ome** [comment]
@shivshankarsomu you have a two way to solve this:

1. Get a testing node of your Redis server and prepare what you need by fixtures and clean it on start.
2. Stub module that works with Redis in your project (Not an easy way to do)
