### ISSUE TITLE
All Phalcon Models are getting patched except one

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#130]
@jails @m1ome 

My all Phalcon's Models are getting Patched except one .
I am not able to see the patched model  in /tmp/kahlan directory.

What might be the reason of api.patcher
 **api.patcher** not patching a particular model?

**Comment by m1ome** [comment]
@shivshankarsomu can you provide your patcher code and model path/name?

**Comment by shivshankarsomu** [comment]
**Patcher Code** 

```
Filter::register('api.patchers', function($chain) {
	$interceptor = Interceptor::instance();
	   $patchers = $interceptor->patchers();
	   $patchers->add('layer', new Layer([
		   'override' => [
  			   'Articles\BarDB',
  			   'Articles\ProductDB',
               'Articles\ProductDB\Products',
			    'Articles\FooDB',
  			   'Phalcon\Mvc\Model'
  		   ]
  	   ]));
 	   return $chain->next();
});
```
Model Path Name **Articles\ProductDB\Products**

All the Models of ProductDB is successfully except **Products model**.

**Comment by m1ome** [comment]
@shivshankarsomu can you give this model namespace definition?

**Comment by shivshankarsomu** [comment]
Spec\Suite\Articles\ProductDB

**Comment by m1ome** [comment]
@shivshankarsomu and other models? why this model lays in Spec?

**Comment by shivshankarsomu** [comment]
No models has namespace Articles\ProductDB

**Comment by jails** [comment]
Please provide a github repo with a reproductible example next time to avoid riddles
