### ISSUE TITLE
How to mock a \Phalcon\Http\Request

### ISSUE THREAD

**Issue by shivshankarsomu** [crysalead/kahlan#132]
@jails @m1ome 
I am unable to mock **\Phalcon\Http\Request** get and post methods.

Can u please guide with the **sample code**.

**Comment by jails** [comment]
Phalcon is a is a C-extension (i.e. the source code is not in PHP userland) so you can't stub any of its classes directly.
The only option is to Monkey Patch the 'Phalcon\Http\Request' class by a compatible mock in  PHP userland.
```php
Monkey::patch('Phalcon\Http\Request', 'Your\Http\RequestMock');
```

**Comment by shivshankarsomu** [comment]
@jails @m1ome 

I used Monkey patching but then also it didnot work 

`use Kahlan\Plugin\Stub;
use Kahlan\Plugin\Monkey;
use Exception;
class SampleController{
public function postAction(){
		if($this->request->isPost()){
				echo "getting post data";
		} else {
			echo "not getting post data";
		}
	}	




}

function mock_http_request(){
	return true;
}

describe("SampleController Controller test", function() {
    it("Tests postAction function", function() {
        $samplecon = new SampleController();
        $phalcon = new \Phalcon\Http\Request();
        Monkey::patch($phalcon->request->isPost,'CB\Spec\Suite\Controllers\http_request'); 
        $samplecon->contactmailerAction();
        
    });
    
});

`

**Comment by m1ome** [comment]
@shivshankarsomu you know that `\Phalcon\Http\Request` and `$this->request` in controller are different things. `$this->request` created by DI container in e.g. just imagine that somewhere in your code is somehing like this:

```php
$di->set("request", 'Phalcon\Http\Request');
```

You just don't see it.
In case you wanna play with this one you should overwrite this one by your usecase.
In e.g. something like this:

```php
$di->set("request", function () {
    $request = Stub::create(['extends' => 'Phalcon\Http\Request', 'layer' => true]);
    Stub::on($request)->method('getUserAgent')->andReturn('stubbed');
    return $request;
});

```

**Comment by m1ome** [comment]
@shivshankarsomu you can use this handy example to view all things together [Phalcon integration](https://github.com/m1ome/kalhan_phalcon)

**Comment by angelxmoreno** [comment]
@shivshankarsomu did you get it to work? the suggestion @m1ome made is what I've been doing for all Phalcon classes. You basically need to inject into the DI all the Phalcon classes you need to interact with but with a stubbed version.
