### ISSUE TITLE
`->toReceive` does not work for anonymous classes

### ISSUE THREAD

**Issue by ilsenem** [crysalead/kahlan#134]
This wont work:

```php
$test = new class {
    public function foo() {}
};

expect($test)->toReceive('foo');

$test->foo();
```

Output:

```
expect->toReceive() failed in `/spec/testSpec.php` line 10

actual received:
    | (array) []
expected:
    | (string) "foo" 
```

**Comment by jails** [comment]
One of PHP's assumptions is that once you define a function/constant/class it stays defined forever. So the only way for Kahlan is to perform some "Just In Time" code rewriting to allow Stubing & Monkey patching out of the box through Composer.

So if you try to Stub or Monkey patch somthing inside a spec it won't get intercepted by JIT patchers and won't be patched. So to sum up all the code present in `*Spec.php` files are not intercepted and therefore not patchable.

Moreover the fact that there's not way to identify an anonymous class by definition, you can't stub it. And being able to stub an anonymous class in `*Spec.php` files is not interesting.

If you are injecting an anonymous class somewhere just pass a `Stub::create()` instance instead, this way you will be able to stub it.

**Comment by ilsenem** [comment]
Oh, is see. I have missed this in documentation, sorry. I have implemented this behavior through `Stub` plugin on the first hand, but tried move to anonymous classes.

Thanks for reply and for beautiful and efficient tool.
