### ISSUE TITLE
Please improve the documentation

### ISSUE THREAD

**Issue by Vesuvium** [crysalead/kahlan#138]
Hi, I found out kahlan and it's awesome! However I found the documentation confusing and missing some key points:

* Config: should list all options in documentation sections and explain them
* Stubs: missing description on what stubs should be used for
* It would be nice if the first example of code (the one in the overview) was written fully, from the <?php tag rather than beginning straight with a describe statement

**Comment by m1ome** [comment]
@jails if you don't mind i can assign this one to myself.

**Comment by m1ome** [comment]
@Vesuvium about **Stubs** - it's kinda crazy to write down in testing framework why someone should use stubs, btw.

**Comment by Vesuvium** [comment]
@m1ome Depends :) If you assume only experienced programmers will use kahlan, yes; but not everyone is, and the concept of stubbing might be new to them. I didn't mean it to be a detailed explanation: in Monkey Patching it explained what it should be used for, in two lines. 

Of course, there also the consideration of me actually being crazy :D

**Comment by jails** [comment]
@m1ome sure, you are assigned now ^^ !

@Vesuvium, stubs are used to isolate parts of your application from each other for unit testing. Let's take the following example:

```php
class Registration {
    public function register($user) {
        if ($success = $user->save()) {
            Mailer::send($user->email, "Welcome to our website");
        }
        return $success;
    }
}
```
But to make clean unit tests you want to test the saving process and the email notification part separatly.

So you'll use a stub to bail out emailing like so:

```php
use App\Registration;
use App\Util\Mailer;
use App\Model\User;

use Kahlan\Plugin\Stub;

describe("->registration()", function() {
    beforeEeach(function() {
        // Just bail out `Mailer::send()`
        Stub::on(Mailer::class)->method('::send')->toReturn(true);
    });
    it("returns `true` on success", function() {
        $registration = new Registration();
        $actual = $registration->register(new User([
            'name'  => 'Willy Boy',
            'email' => 'willy.boy@email.com'
        ]));
        expect($actual)->toBe(true);
    });
});
```

But be careful, stubing and monkey patching are poweful tools but they should only be used when necessary.

**Comment by jails** [comment]
@m1ome still on it ?

**Comment by m1ome** [comment]
@jails yeah i think i will try to move forward on weekends.

**Comment by jails** [comment]
Fixed by https://github.com/crysalead/kahlan/commit/79def52b1df3ebd843ee3fcdc8db81113c258388 and https://github.com/crysalead/kahlan/commit/73e77667d8b09b76e1edc3b01e415afef33dc312
