### ISSUE TITLE
Stubs a method example not behaving as expected

### ISSUE THREAD

**Issue by pjullah** [crysalead/kahlan#145]
Hi

I'm following the documentation on Method Stubbing - http://kahlan.readthedocs.io/en/latest/stubs/ - and experiencing unexpected behaviour.

I've created a TestClass with a method that I would, having read the documentation, expect to be overridden, which isn't.

    it('stubs a method', function() {

        class TestClass {
            public function returnAString() {
                return 'this string SHOULD NOT be returned';
            }
        }

        $collaborator = new TestClass();

        Stub::on($collaborator)->method('returnAString')->andReturn('this string SHOULD be returned');

        expect($collaborator->returnAString())->toEqual('this string SHOULD be returned');

    }); 

The output from running spec is:
![screen shot 2016-08-19 at 10 53 00](https://cloud.githubusercontent.com/assets/1737749/17806221/27576528-65fb-11e6-82ca-f3d2d4ff901b.png)

Is what I am experiencing the intended behaviour?

Thanks

**Comment by jails** [comment]
As stated in the documentation: "code in *Spec.php files are not intercepted and patched". Which means `TestClass::returnAString()` can't be stubbed if not loaded through Composer.

So by default only classes present in the `src` directory and imported through the `use statement` can be stubbed.

If you want to use a file from the spec directory you should update your composer.json that way:

```js
"autoload": {
   "psr-4": {
       "MyProject\\": "src/",
       "MyProject\\Spec\\": "spec/"
   }
}
```
Then run composer udpate.

Copy your `TestClass.php` file in a `spec\Mock` directory for example then add `use Myproject\Spec\Mock\TestClass;` in top of your spec file. Then your test should pass.

**Comment by pjullah** [comment]
Thanks for the quick response. 

The example I posted was contrived to demonstrate what I was experiencing. The actual test concerns intercepting calls to \MongoCollection->update()

For reasons that I'm yet to discover, I was not able to create a replacement for the \MongoCollection using Stub::create so I opted for an alternative, namely creating a real instance of this class, and then attempting to override the update() method. My initial example attempted to replicate this for simplicity. 

The problem that I am experiencing is that, having stipulated that I which to override the update() it would appear that the application is still attempting to connect to a Mongo.

![screen shot 2016-08-19 at 11 21 29](https://cloud.githubusercontent.com/assets/1737749/17806926/50dc1b56-65ff-11e6-8ef1-74db1602be3d.png)

The actual test that I am working with is;

    context('->where', function() {

        it('should set query fields', function() {

            $mongo_client = new \MongoClient('mongodb://localhost:27017', ['connect' => false]);

            $database = $mongo_client->selectDB('test');

            $collection = new \MongoCollection($database, 'test');

            Stub::on($collection)->method('update')->andReturn(true);

            $sut = new Updater($collection);

            $sut->where('field', 'value');
            $sut->run();

            expect($collection)->toReceive('update')->with(
                ['field' => 'value'],
                [],
                []
            );
        });
    });

 I completely accept the explanation you have provided, but in that case how can I stub a native PHP class/method?

Thanks again for your help.

**Comment by pjullah** [comment]
P.S - what I wanted to do was something like;

$collection = Stub::create(['extends' => ['\MongoCollection']]);

But the constructor got in the way. I needed to specify the __construct method in the create(), passing it's dependancies, i.e. a \MongoDB instance.

I wouldn't of actually ended up with fewer LOC.

Thinking on it, I would of created a stub for the MongoDB too, and that might be what I end up doing, but I shouldn't have to if I can overrode the update() in \MongoCollection.

**Comment by jails** [comment]
Kahlan is not able to stub PHP core classes directly. However there's a couple of alternative to deal with such code.

If you are annoyed by the construct you can use the following:
```php
$collection = Stub::create([
    'extends' => 'MongoCollection';
    'methods' => ['__construct']
]);
```
The other alternative is to monkey patch everything:

```php
$mongoClient = Stub::classname();
$mongoCollection = Stub::classname();

Monkey::patch('MongoClient', $mongoClient);
Monkey::patch('MongoCollection', $mongoCollection);

//run you logic

expect($mongoCollection)->toReceive('update')->with(
    ['field' => 'value'],
    [],
    []
);
```

Anyway this kind of test can be a bit tricky, and when possible I would perform integration tests for this kind of "core logic".
And then put a stub on a higher level of abstraction like a "Model::save()" method to be able to unit test PHP userland logic.

**Comment by pjullah** [comment]
I hope I haven't made you feel I'm annoyed, I think this is a great framework and appreciate the work you've put in. I've been using PHPUnit and this is a breath of fresh air, genuinely. 

If I may ask one final question?

I've just done as you suggested and constructed the \MongoCollection; 

$collection = Stub::create([
    'extends' => 'MongoCollection';
    'methods' => ['__construct']
]);

However, I receive a \MongoException

![screen shot 2016-08-19 at 12 02 41](https://cloud.githubusercontent.com/assets/1737749/17807930/dd19361c-6604-11e6-8e33-1bba2e95ed01.png)

Is there any way to overcome this? (apart from the Monkey Patching approach you've suggested)

**Comment by jails** [comment]
Oh no not at all I'm also facing the same issues, but at least with Kahlan you have some way to deal with them. 

I think you get this error because you called the `update()` on the mongo collection method which can't work since it hasn't been initialized correctly so I would suggest to stub all this methods if you need a return value or simply with:

```php
$collection = Stub::create([
    'extends' => 'MongoCollection';
    'methods' => ['__construct', 'update', etc.]
]);
```

**Comment by pjullah** [comment]
I feel like I'm getting a little closer;

```php
    context('->where', function() {

        it('should set query fields', function() {

            $collection = Stub::create([
                'extends' => 'MongoCollection',
                'methods' => ['__construct', 'update']
            ]);

            $sut = new Updater($collection);

            $sut->where('field', 'value');
            $sut->run();

            expect($collection)->toReceive('update')->with(
                ['field' => 'value'],
                [],
                []
            );
        });
    });
```
![screen shot 2016-08-19 at 12 29 43](https://cloud.githubusercontent.com/assets/1737749/17808569/a7dd76ee-6608-11e6-9aec-fedb1ea395e9.png)

So I tried this instead;

```php
    context('->where', function() {

        it('should set query fields', function() {

            $collection = Stub::create([
                'extends' => 'MongoCollection',
                'methods' => ['__construct']
            ]);

            Stub::on($collection)->method('update')->andReturn(true);

            $sut = new Updater($collection);

            $sut->where('field', 'value');
            $sut->run();

            expect($collection)->toReceive('update')->with(
                ['field' => 'value'],
                [],
                []
            );
        });
    });
```

But then get;

![screen shot 2016-08-19 at 12 31 40](https://cloud.githubusercontent.com/assets/1737749/17808609/e7a0c790-6608-11e6-9ff7-ed0560f3617b.png)

Looking at the API, create() accepts a 'params' array which is passed to the __constructor (not sure why I'm telling you that, you wrote it!)

So I've attempted to pass a \MongoDB stub, which requires a \MongoClient stub;

```PHP    
    context('->where', function() {

        it('should set query fields', function() {

            $client = Stub::create([
                'extends' => 'MongoClient',
                'params' => ['mongodb://testing:123']
            ]);

            $db = Stub::create([
                'extends' => 'MongoDB',
                'params' => [$client]
            ]);

            $collection = Stub::create([
                'extends' => 'MongoCollection',
                'methods' => ['__construct'],
                'params' => [$db, 'test']
            ]);

            Stub::on($collection)->method('update')->andReturn(true);

            $sut = new Updater($collection);

            $sut->where('field', 'value');
            $sut->run();

            expect($collection)->toReceive('update')->with(
                ['field' => 'value'],
                [],
                []
            );
        });
    });
```

But it still tries to connect to the database;

![screen shot 2016-08-19 at 12 41 24](https://cloud.githubusercontent.com/assets/1737749/17808832/47b05f46-660a-11e6-99ab-a10d17809478.png)

I feel that there might be some millage in monkey patching the \MongoDB class, but it just feels like

```PHP
Stub::on($collection)->method('update')->andReturn(true);
```

should be intercepting the calls.

I think I'm going to get some lunch, and think of a different way of approaching the problem.

**Comment by jails** [comment]
Yeah your second option is the way to go, but I forgot to talk about the `'layer'` option.
```php
context('->where', function() {

        it('should set query fields', function() {

            $collection = Stub::create([
                'extends' => 'MongoCollection',
                'methods' => ['__construct'],
                'layer' => true
            ]);

            Stub::on($collection)->method('update')->andReturn(true);

            $sut = new Updater($collection);

            $sut->where('field', 'value');
            $sut->run();

            expect($collection)->toReceive('update')->with(
                ['field' => 'value'],
                [],
                []
            );
        });
    });
```

The layer option just override all parent's methods so you can stub them. This solve problems related to core classes which are not in PHP userland.

**Comment by pjullah** [comment]
Just got back from lunch, and found your solution.

I can confirm it works perfectly.

Thank you for your help today, it was really appreciated.

**Comment by jails** [comment]
You bet !
