### ISSUE TITLE
Coverage.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#15]
When i am trying to run `bin/kahlan --config="kahlan-config.travis.php" --coverage="kahlan\plugin\Call"`.

It outputs:

```
Coverage Summary
----------------

Unexisting namespace: `kahlan\plugin\Call`, coverage can't be generated.
```

It is a quite strange.

**Comment by jails** [comment]
Weird, it's working for me on a clean install.

**Comment by m1ome** [comment]
I am reproducing it with a clean install. Any suggestions how to trace this.

**Comment by jails** [comment]
Also tried to running it with HHVM and it works. Try to clean up caches `rm -rf /tmp/kahlan` and run it again.
What php version are you using ?
Does `bin/kahlan --config="kahlan-config.travis.php" --coverage="kahlan\plugin"` spit out the `kahlan\plugin\Call.php` file ?

**Comment by m1ome** [comment]
```
PHP 5.5.20-1+deb.sury.org~precise+1 (cli) (built: Dec 21 2014 19:54:33) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

**Comment by m1ome** [comment]
Removed cache and still the same.

**Comment by m1ome** [comment]
Yes `bin/kahlan --config="kahlan-config.travis.php" --coverage="kahlan\plugin"` echo a coverage on plugin\Call.php

**Comment by jails** [comment]
Are you running it inside a vagrant box or something ?

**Comment by jails** [comment]
The displayed error is this one: https://github.com/crysalead/kahlan/blob/master/src/reporter/Coverage.php#L266

you should be able to do a:
```
print_r(array_keys($this->metrics()->get("kahlan\plugin")));
```
And you should see all classes inside plugin.
but if 'plugin\Call.php' has been spitted out, there's no reason:
```
print_r(array_keys($this->metrics()->get("kahlan\plugin\Call")));
```
can't display the correct information.

**Comment by m1ome** [comment]
Yes, i am running inside a vagrant.

**Comment by jails** [comment]
Still not able to reproduce on travis (https://travis-ci.org/crysalead/kahlan/builds/49312153). Feel free to reopen if you find the root cause.

**Comment by m1ome** [comment]
Find a bug. Fix it on https://github.com/crysalead/jit/pull/1
