### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by damiandziaduch** [crysalead/kahlan#153]
https://github.com/crysalead/kahlan/blob/master/docs/config-file.md

There is a link "You can see more details about how the workflow works here (start reading with the run() method)." which is broken. Is right before section https://github.com/crysalead/kahlan/blob/master/docs/config-file.md#optimizations

**Comment by jails** [comment]
Good catch, fixed on the `dev` branch https://github.com/crysalead/kahlan/commit/63f54a4658a3aaa07eb5990662e6bd16f79c8566

**Comment by damiandziaduch** [comment]
👍
