### ISSUE TITLE
TYPO matchers.md 

### ISSUE THREAD

**Issue by pawelwnuq** [crysalead/kahlan#156]
Hi,
There is a typo in matchers.md:282
There is ->time function which does not exist.
It should be:
`expect($foo)->toReceive('::message')->with('My Message')->times(2);`

**Comment by jails** [comment]
Good catch :+1: 
Can you open a pull request on the `dev` branch ?

**Comment by pawelwnuq** [comment]
sure - 
https://github.com/crysalead/kahlan/pull/157

**Comment by jails** [comment]
Merged in https://github.com/crysalead/kahlan/commit/e0bb6a45ef6e66ce5039a098bc11ebc0738e3e57
