### ISSUE TITLE
Question: how to stub static method Foo::bar()?

### ISSUE THREAD

**Issue by wulftone** [crysalead/kahlan#160]
I have been trying to figure this out for a while but I am not having much success.  Is it possible to stub a method that is invoked like `Foo::bar()`?  I saw examples of some other things in your documentation but they did not seem to be working like I expected.

I know this is wrong, but this captures the spirit of what I am trying to accomplish:
```php
<?php

use Kahlan\Plugin\Stub;

class Foo {
    public static function bar() {
        return 'bar';
    }
}

describe("Foo", function() {
    it('should bar', function() {
        Stub::on('Foo')->method('::bar')->andReturn('beep');
        expect(Foo::bar())->toBe('beep');
    });
});
```

It's very trivial in Ruby (Khalan seems based on Ruby's `rspec`), but this may not be possible in PHP?  This kind of thing happens all over the place in many libraries and in our own legacy code, so it'd be awesome to figure out how to mock like this without huge refactors into instance methods.  Any ideas?

**Comment by jails** [comment]
If `Foo` is a class loaded by composer i.e not in a spec file and not loaded using `require('some/file/path/Foo.php')` yes it's the correct way to stub a static method.

Working example: https://github.com/jails/temp/tree/static-method

**Comment by wulftone** [comment]
Hmm the example is throwing an unrelated exception:
```
PHP Fatal error:  Uncaught Error: Class 'filter\Filter' not found in /home/me/temp/kahlan-config.php:4
Stack trace:
#0 /home/me/temp/vendor/crysalead/kahlan/src/Cli/Kahlan.php(190): require()
#1 /home/me/temp/vendor/crysalead/kahlan/src/Cli/Kahlan.php(193): Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Cli\Args))
#2 /home/me/temp/vendor/crysalead/kahlan/bin/kahlan(46): Kahlan\Cli\Kahlan->loadConfig(Array)
#3 {main}
  thrown in /home/me/temp/kahlan-config.php on line 4
```
Maybe I started khalan wrong, I did `./bin/khalan` with no arguments..?

**Comment by jails** [comment]
checkout the `static-method` branch (not the master branch which is deprecated and rely to Kahlan 1.x) the link above should be accurate.

**Comment by wulftone** [comment]
oh gotcha, thank you

**Comment by wulftone** [comment]
Now knowing this, I suspect my real problem has to do with the Yii autoloader/importer thing... I'll have to read a bit and see if khalan can handle Yii's odd way of doing things

**Comment by jails** [comment]
Imo the best option here is to not require the Yii autoloader when running specs.

```php
if (defined('KAHLAN_VERSION')) {
    // the yii autoloader.
}
```
and set up the composer.json correcly with Yii namespace. Since Yii is PSR4 compatible, composer should be able to do the job correcly.

The other option is to create a custom interceptor for the Yii framework which is a bit more complicated.

Whatever you find, feel free to open a PR to update https://github.com/crysalead/kahlan/blob/master/docs/integration.md with your Yii discoveries.
