### ISSUE TITLE
[BUG] toThrow

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#17]
If you traverse a `toThrow` matcher you will see that a closure will be called twice. It's a real bug, at my opinion.

**Comment by jails** [comment]
All matchers return a boolean on `::match()`. However if the expectation fail, the reporter need some details about the failure, so the `::description()` method run the expectation to build a detailled report of the failure.

**Comment by m1ome** [comment]
Why you can't save an exception in state?

**Comment by jails** [comment]
Behavior modified in https://github.com/crysalead/kahlan/commit/d3dea7f3e25730628d4c9d3024b94bbf7290cf5e

**Comment by m1ome** [comment]
:+1:
