### ISSUE TITLE
Do Kahlan have any todo board or something like this? 

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#21]
It will be pretty awesome that someone could help you to implement ideas you have in your mind. Is there is any board you can share this ideas?

**Comment by jails** [comment]
Since all the features I wanted in has been included in 1.0.0, I think I'll need to spend some more time using Kahlan to discover if there's still some specific points which can be enhanced. So here are the only point I'm in mind https://github.com/crysalead/kahlan/wiki/Roadmap right now.

**Comment by m1ome** [comment]
:+1:
