### ISSUE TITLE
[BUG] After last update something wrong with a Stub.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#32]
I have a stub:

```php
Stub::on('Api\Models\AtmLog')->method('create', function($data=null, $whitelist=null) {
    return false;
});
```

`Api\Models\AtmLog`: 

```php
class ApiLog extends \Spec\Helper\BaseModel {
}
```

`\Spec\Helper\BaseModel`:

```php
<?php
class BaseModel extends \Phalcon\Mvc\Model {

  public static function find($parameters=null){
    return parent::find($parameters);
  }

  public static function findFirst($parameters=null){
    return parent::findFirst($parameters);
  }

  public function save($data=null, $whiteList=null){
    return parent::save($data, $whiteList);
  }

  public function create($data=null, $whiteList=null){
    return parent::create($data, $whiteList);
  }

  public function delete() {
    return parent::delete();
  }
}
```

It correctly passes into create if i dump `get_class($this)` in `create` it will show `Api\Models\ApiLog` but `Stub` doesn't work. Maybe some BC was broken?

**Comment by m1ome** [comment]
Version 1.0.0 is fine.

**Comment by m1ome** [comment]
It's bug in `1.0.6` checked and `1.0.5` passed test.

**Comment by m1ome** [comment]
I think 122550320dc6e7f80e263fec1e0e5f97ad3af4a5 can break a BC.

**Comment by jails** [comment]
Weird, I'm not able to reproduce. https://github.com/jails/temp/commit/bd61dcdaf2380905ecf6f9ff4f7baa102afe441d gives https://travis-ci.org/jails/temp/jobs/51644921 so looks like the method is corrected intercepted in the above example.

**Comment by m1ome** [comment]
How can i dump stubbed methods or something else? To provide more debug info.

**Comment by jails** [comment]
`Stub::registered()` should return all stubbed methods but if there's a glitch somewhere, the easier way would be to clone https://github.com/jails/temp (the dev branch) and tweak it to reproduce your actual issue on it because I probably missed something somewhere since I wasn't able to reproduce it.

**Comment by m1ome** [comment]
I'll try it tomorrow.

**Comment by m1ome** [comment]
Found it, it was not BC but, a strange work.
I have a code:

```php
$args->set('include', [
  'Api'
]);
```

And before `1.0.6` it worked fine, but my base model is inside `Spec\Helper` in `1.0.6` i add:

```php
$args->set('include', [
  'Api',
  'Spec\Helper',
]);
```

And it work.

**Comment by jails** [comment]
Ah indeed, it's probably related to this commit https://github.com/crysalead/kahlan/commit/03c910cedcc85a14e688a4a0a6539f0657358683
All `$args->set()` calls in config files was just ignored before this commit. Previously the only option to "set" a specific value to an argument was to override its defaults values using `$args->argument()`. And the fact that `$args->set()` is now working as expected was probably the origin of your issue.

**Comment by m1ome** [comment]
I think so. It's not a BC break, more like correct work. Thanks.
