### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#33]
I am trying to override a Phalcon model based method "find, findFirst" and e.t.c.
They are inside c-extension. Could them be override over Monkey patching ?

Or there is some way to do this overload default model namespace through Interceptor?

**Comment by jails** [comment]
Monkey patching only works if you are calling explicitly a "built-in function" or instantiating a "built-in class". But it doesn't work for "built-in inheritance" unfortunately. The only solution would be to introduce a new patcher imo ([like described here](https://github.com/crysalead/kahlan/issues/5#issuecomment-72183225)).

**Comment by m1ome** [comment]
It looks like in solution line links is broken.

**Comment by jails** [comment]
It's just a comment of the issue n°5

**Comment by m1ome** [comment]
You mean write a patcher something like Quit patcher and inject it into patcher namespace. https://github.com/crysalead/kahlan/blob/master/src/cli/Kahlan.php#L352-L365 like here?

**Comment by jails** [comment]
Yup, I mean a patcher which rewrite all:
```php
class MyModel extends \Phalcon\Mvc\Model
```
to something like:
```php
class MyModel extends \a\custom\layer\Class
```

The `a\custom\layer\Class` class could be a class in your spec directory which extends `Phalcon\Mvc\Model` with all its method overridden, or a more complex patcher should be able to create such class automatically. For example by using `$layerClass = Stub::classname(['extends' => 'Phalcon\Mvc\Model'])`. Unfortunately `Stub::classname()` won't work out of the box since right now the only "layered methods" are the abstract one but I think I can sketch up something quickly.

**Comment by jails** [comment]
Just updated the Stub class to allow a `layer` parameter https://github.com/crysalead/kahlan/commit/453787c8202cb3e212db11530aa6ce08eae379ca

So the deal is replace all `extends \Phalcon\Mvc\Model` to  `extends \$layerClass` where `$layerClass` is `$layerClass = Stub::classname(['extends' => 'Phalcon\Mvc\Model', 'layer' => true])`.

**Comment by jails** [comment]
And I sketched up the principle of a layer patcher in this commit https://github.com/crysalead/kahlan/commit/f74002c9b80271749dd6b8eef97980d5528b2e0a in the dev branch.

**Comment by jails** [comment]
So on the dev branch adding the following:
```php
     ...
     $patchers->add('layer', new Layer([
         'Phalcon\Mvc\Model'
     ]));
```
using the [patchers endpoint](https://github.com/crysalead/kahlan/blob/master/src/cli/Kahlan.php#L352-L365) should allow you to stub any kind of model's methods.

Feel free to keep me updated if this patcher still have room for improvement according to your specific usage.

**Comment by m1ome** [comment]
Iside config i set:

```php
Filter::register('app.patchers', function($chain) {
	$interceptor = Interceptor::instance();
	$patchers = $interceptor->patchers();
	$patchers->add('layer', new Layer([
		'override' => [
			'Phalcon\Mvc\Model'
		]
	]));

	return $chain->next();
});
```

Then i have a model:

```
<?php
namespace Api\Models;

class ApiLog extends \Phalcon\Mvc\Model {

}
```

And spec:

```php
<?php

use kahlan\plugin\Stub;

describe("Stub with a layer filter", function() {

	it("should stub a layer", function() {

		Stub::on('Api\Models\ApiLog')->method('create', function($data=null, $whiteList=null) {
			return true;
		});	

		$model = new \Api\Models\ApiLog();
		expect($model->create())->toBe(true);

	});

});
```

And it fails. (It return `false`)

**Comment by m1ome** [comment]
After i clean-up `/tmp/kalhan` it seems start working layering. But i got an error:

```php
PHP Fatal error:  Cannot override final method Phalcon\Mvc\Model::__construct() in /vagrant/crm/phalcon_test/temp/vendor/crysalead/kahlan/src/plugin/Stub.php(226) : eval()'d code on line 73
```

It seems that no need in layer to patch-up a `finally` methods.

**Comment by m1ome** [comment]
Fixed this adding on `plugin/Stub:432` line:

```php
if ($method->getModifiers() & ReflectionMethod::IS_FINAL) continue;
```

And got new error:

```php
PHP Fatal error:  Declaration of kahlan\spec\plugin\stub\Stub0::assign() must be compatible with Phalcon\Mvc\ModelInterface::assign($data, $columnMap = NULL) in /vagrant/crm/phalcon_test/temp/vendor/crysalead/kahlan/src/plugin/Stub.php(226) : eval()'d code on line 72
```

**Comment by m1ome** [comment]
Fixed this. I will prepare a patch

**Comment by m1ome** [comment]
@jails it works now perfectly.

**Comment by m1ome** [comment]
On a second run i have:

```
PHP Fatal error:  Class 'kahlan\spec\plugin\stub\Stub0' not found in /tmp/kahlan/vagrant/crm/wtm.dev/app/models/Cards.php on line 14
```

This line is:

```php
class Cards extends \kahlan\spec\plugin\stub\Stub0 {
```

**Comment by jails** [comment]
Ah yeah indeed, didn't think about that, I guess we will need to embed the sub inside the cached file.

**Comment by m1ome** [comment]
I think it will be more handy to you.

**Comment by jails** [comment]
I thought about something like that https://github.com/crysalead/kahlan/commit/8a527822f0d9cc02f95cd17699785dd18484e7a9
It should work but wasn't able to test it since I haven't Phalcon installed.

**Comment by m1ome** [comment]
@jails it broken now. Just failing and that's all. I have a file, and it seems to be normal, but it just failing tests.

**Comment by jails** [comment]
@m1ome what the cached file in `/tmp/kahlan` looks like ?

**Comment by m1ome** [comment]
@jails http://pastebin.com/0CWMBivr

**Comment by m1ome** [comment]
Now

```php
PHP Parse error:  syntax error, unexpected '<' in /tmp/kahlan/vagrant/crm/phalcon_test/temp/app/models/ApiLog.php on line 6
```

It looks like you generate `<?php` twice.

**Comment by jails** [comment]
Ah yeah I fucked up the last dev commit.

**Comment by jails** [comment]
Should work better now but you will need to update https://github.com/crysalead/jit to its last master.

**Comment by m1ome** [comment]
@jails yes, now it's working as it should.

**Comment by m1ome** [comment]
@jails thank :+1: !

**Comment by jails** [comment]
Cool, I'm merging it to master then.

**Comment by shivshankarsomu** [comment]
@jails Can u please help us with the undermentioned.
We are using Phalcon PHP for our website MVC Framework.
I am trying to test my all models and Controllers code using KAHLAN.

When I am trying to stub phalcon's Functions (FINDFIRST, GetRelated etc) it is not working.

I even put the API Patcher code in my kahlan-config.php which is given in 

http://kahlan.readthedocs.org/en/latest/integration/#working-with-a-autoloader-not-compatible-with-psr-0

 
PATCHER CODE IN kahlan-config.php

Filter::register('api.patchers', function($chain) {
	$interceptor = Interceptor::instance();
	  $patchers = $interceptor->patchers();
	  $patchers->add('layer', new Kahlan\Jit\Patcher\Layer([
		  'override' => [
			  'Phalcon\Mvc\Model'
		  ]
	  ]));
	  return $chain->next();
});

Filter::apply($this, 'patchers', 'api.patchers');

PFA my model and test files.


My namespaces for model for example 'CB\db\sitedb\match\Match'  and 'CB\db\sitedb\series\Series' are correct because I am able to access all the model data and functions.
 


[files.zip](https://github.com/crysalead/kahlan/files/194865/files.zip)

**Comment by m1ome** [comment]
@shivshankarsomu you need multiple steps for testing `Phalcon`. 
First of all you need to load your models to PSR4-autoloader:
```php
Filter::register('app.namespaces', function($chain) {
  $this->_autoloader->addPsr4('Api\\Models\\', __DIR__ . '/app/models/');
  $this->_autoloader->addPsr4('Api\\Controllers\\V1\\', __DIR__ . '/app/controllers/v1/');
});
```
In e.g. we loading here models & controllers from directories, moving them to namespaces.

Second, you should add a `Layer` to be able to Stub/Mock `Phalcon` C-extension:
```php
Filter::register('app.patchers', function($chain) {
    $interceptor = Interceptor::instance();
    $patchers = $interceptor->patchers();
    $patchers->add('layer', new Layer([
        'override' => [
            'Phalcon\Mvc\Model'
        ]
    ]));

    return $chain->next();
});
```

Third you should be *CORRECT* when passing parameters to stubbed method:
```
        Stub::on('Api\Models\Cards')->method('::findFirst', function($params = null) {
          $card = new stdClass();
          $card->active = 1;

          return $card;
        });
```

As you see i am providing `function($params = null)` and in your files you don't do such thing. For `Stub` system it looks like method will be different from `::findFirst` that uses `Phalcon`.

**Comment by shivshankarsomu** [comment]
@m1ome Thanks for the reply

**I changed the code to this then also it is not working**
     $match_model = new Match();
        $match_model->id = "2214";

		    Stub::on('CB\db\sitedb\match\Match')->method('::findFirst', function($params = null) {
            return $match_model;
        });
        $series_model = new Series();
        $series_model->id = "2223";
        $series_model->series_type = "WC";
        expect($series_model->get_series_months())->toBe($match_model);


Please help me with this

**Comment by m1ome** [comment]
@shivshankarsomu do you loading models like in my first step?

**Comment by shivshankarsomu** [comment]
@m1ome yes

PFB the code.


Filter::register('app.namespace', function($chain) {
    $this->autoloader()->addPsr4('CB\\db\\' ,__DIR__ . 'db/');
    $this->autoloader()->addPsr4('CB\\helpers\\' ,__DIR__ . 'helpers/');
    $this->autoloader()->addPsr4('CB\\controllers\\', __DIR__ . 'controllers/');
});

 Filter::register('api.patchers', function($chain) {
	$interceptor = Interceptor::instance();
	   $patchers = $interceptor->patchers();
	   $patchers->add('layer', new Kahlan\Jit\Patcher\Layer([
		   'override' => [
			   'Phalcon\Mvc\Model'
		   ]
	   ]));
	   return $chain->next();
});
Filter::apply($this, 'patchers', 'api.patchers');
Filter::apply($this, 'namespaces', 'app.namespace');

**Comment by jails** [comment]
Can you please create a github repo with your code sample so we can clone it ? It'll be easier for us to get the issue by playing with your code.

**Comment by shivshankarsomu** [comment]
@jails @@m1ome 

I had some configuration issue while mocking Phalcon ::findFirst  which got fixed.

But now I am facing some issue while mocking  **Phalcon getRelated** can you please share some examples of mocking  **Phalcon getRelated**

**Comment by m1ome** [comment]
@shivshankarsomu https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.9/Phalcon/mvc/Model.php#L1089

**Comment by m1ome** [comment]
@shivshankarsomu code should look like this:
```php
Stub::on('Api\Models\Cards')->method('::getRelated', function($alias, $arguments = null) {
  $card = new stdClass();
  $card->active = 1;

  return $card;
});
```

**Comment by m1ome** [comment]
```php
$cards = Api\Models\Cards::findFirst();
Stub::on($cards)->method('getRelated', function($alias, $arguments = null) {
  $card = new stdClass();
  $card->active = 1;

  return $card;
});
```

**Comment by shivshankarsomu** [comment]
Thanks for the help @m1ome @jails 
It worked.

**Comment by m1ome** [comment]
@shivshankarsomu you are welcome. Next time please use another issue to ask a question. Feel free to do it.
