### ISSUE TITLE
Implement autoloader injection.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#43]
Maybe better way that user `$this->_autoloader` inside scope implement shortcut to autoloader?

**Comment by jails** [comment]
Hmm not sure to get what you meant.

**Comment by m1ome** [comment]
To overload default autoloader (or to add new path) we need to write something like:

```php
$this->_autoloader->addPsr4(...);
```

In my opinion this more looks like a hack.

**Comment by jails** [comment]
Imo you should be able to use the getter:
```php
$this->autoloader()->addPsr4(...);
```

**Comment by m1ome** [comment]
Then `_autoloader` should be private maybe?

**Comment by jails** [comment]
The filtering system gives you a full context access of filterable methods. Changing `protected` to `private` won't change anything afaik.
Moreover the `private` keyword is a bad oop practice it shouldn't be used.

**Comment by m1ome** [comment]
Then i think i should rewrite a doc for Phalcon.
I used here a _autoloader
