### ISSUE TITLE
Added Kahlan to php-awesome

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#44]
I think it will be awesome in Kahlan can be in `awesome-php`.
I added it there - https://github.com/ziadoz/awesome-php/pull/351/files

**Comment by jails** [comment]
Haha already opened a PR a couple of days ago https://github.com/ziadoz/awesome-php/pull/333 but looks like the author don't want to include it ;-)

**Comment by jails** [comment]
For visitors who are stumbling on this issue and want Kahlan to be included in php-awesome just [go there](https://github.com/ziadoz/awesome-php/pull/351) and vote up. Thanks.

**Comment by m1ome** [comment]
Updated my PR with your starting comment.
