### ISSUE TITLE
Need improvements in functionality.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#46]
Currently **Kahlan** need some improvements in functionality:

- [x] Add a command to check up current installed kahlan version
- [x] Add a clear-cache command (to run up a clear run on Kahlan)
- [x] Drop cache after new version (maybe some workaround after composer update?)

**Comment by m1ome** [comment]
Take a look at [Scripts](https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-)

**Comment by m1ome** [comment]
Implemented a "--cc". Please review @jails.

**Comment by m1ome** [comment]
Added cache clearing on "composer update". Need to test it properly.

**Comment by m1ome** [comment]
Added version handling concept. I think there is a strong need to think about mechanism of versions inside code.

**Comment by jails** [comment]
Implemented in https://github.com/crysalead/kahlan/pull/49
