### ISSUE TITLE
Controlling error reporting level.

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#54]
Is there a way to control error reporting level of invoked code? Better globally for all suites...

This code
```php
describe('example', function () {
    it('produces notice exception', function () {
        error_reporting(E_ALL ^ E_NOTICE ^ E_STRICT);
        $arr = [];
        expect($arr['some'])->toBe(2);
    });
});
```
produces next output:
```
example
  ✘ it produces notice exception
    an uncaught exception has been thrown in `/spec/SomeSpec.php` line 12
    
    message:`kahlan\PhpErrorException` Code(0) with message "`E_NOTICE` Undefined index: some"
```

**Comment by jails** [comment]
Not sure to understand your use case since all errors should always be reported. However if you need to check that some missing parameter should throw an exception. You should write it that way:

```php
    describe('example', function () {
        it('assures a notice exception is generated', function () {
            $closure = function() {
                $arr = [];
                $arr['some'];
            };
            expect($closure)->toThrow(new \kahlan\PhpErrorException());
        });
    });
```

**Comment by tyranron** [comment]
> all errors should always be reported especially inside a test environment
I wish to be this true.
But...
If we have code that is running under `E_ALL ^ E_NOTICE ^ E_STRICT` error reporting level and was written according to this error reporting level, so situations like this
```php
$arr = [];
$arr['some'];
```
do not count as errors (kinda project agreement), and we want to test this code with those PHP settings that it runs exactly under.
So, by default (`E_ALL`), this code produces `E_NOTICE` exception which is not expected behaviour according to project agreement (cause when projects is running normally, such error do not appear because of different error reporting level).
And my question is:
Is there any way to setup custom error reporting level for running tests in environment with expected code behaviour? Or `kahlan` tests can only be applied to code that was designed and written expecting `E_ALL` error reporting level?

**Comment by jails** [comment]
Ok I see it's for managing legacy code. Just added https://github.com/crysalead/kahlan/commit/6c63defd00eac7d72d4272d79b587ae8610eb57a on the last master so you should be able to create a `kahlan-config.php` file with the following content:
```php
<?php
error_reporting(E_ALL ^ E_NOTICE ^ E_STRICT);
```
And it would override the error reporting level of the test environment globally.

**Comment by tyranron** [comment]
Yay, it works now. Thanks a lot for fast reaction!

**Comment by nbdh** [comment]
It seems the ability to control the error reporting level in `kahlan-config.php` was broken in https://github.com/kahlan/kahlan/commit/79d1058639140848ad84bd513e94ecb1b0f91106 - as [error_reporting(E_ALL) is now called again after](https://github.com/kahlan/kahlan/blob/ff2449502f2ae9ee48d3555ce5d285505ab6375b/bin/kahlan/#L70)  [`Kahlan::loadConfig()`](  https://github.com/kahlan/kahlan/blob/ff2449502f2ae9ee48d3555ce5d285505ab6375b/bin/kahlan/#L39).

Is there another way of achieving what @tyranron asked for back then? If not I should probably open a new issue.

**Comment by jails** [comment]
You should be able to do it with [filters](https://kahlan.github.io/docs/config-file.html) in your `kahlan-config.php` file.

```php
Filters::apply($this, 'run', function($next) {
    error_reporting(0);
    return $next();
});
```

**Comment by nbdh** [comment]
@jails Indeed! Works like expected.

Thanks for the super quick help on this one and your great work on this project in general!
