### ISSUE TITLE
Question about Stub.

### ISSUE THREAD

**Issue by m1ome** [crysalead/kahlan#61]
Hello, i have a question about stub. Let's pretend i have a controller similar to:

```php

$client = new Client();

if (!$client->save()) {
    throw new Exception("Some strange exception");
}

if ($client->age > 30) {
    $client->is_overaged = true;
    if (!$client->save()){
         throw new Exception("Some second strange exception");
    }
}

```

How can i stub second exception? It's a second call of `->save()` function.

**Comment by jails** [comment]
Afaik,

```php
Stub::on("my\name\space\Client")->method('save')->andReturn(true, false);
```
Should work out of the box.

**Comment by m1ome** [comment]
No, it's not a right way. It will not be saved correcly and if should work in id something like `$client->id` in a code it would not be possible. The right way is: 
- On the first run call normal `save`
- On the second run call stubbed `save`

Is it possible?

**Comment by jails** [comment]
Afaik you will need to manage the flow on your own.

```php
Stub::on("my\name\space\Client")->method('save', function($data, $options) {
    if (!$this->is_overaged) { // or some other condition
        return parent::save($data, $options);
    }
    return false;
});
```

**Comment by m1ome** [comment]
In my variant i have this:

```php
      fit("should throw on payment state change", function() {

        Stub::on('Api\Models\Payment')->method('save', function($data = null, $whitelist = null) {
          if ($this->status === 'manual') { 
            return false;
          } else {
            parent::save($data, $whitelist);
            return true;
          }
        });

        $this->request['timestamp'] = $this->request['timestamp'] + 1;
        $this->request['money']['clear_amount'] = 1000;
        $this->request['money']['balance_amount'] = 500;

        $this->controller->setRequest($this->request);
        expect(function() {
          $this->controller->run('terminal');
        })->toThrowLogic(ExceptionCodes::INTERNAL_ERROR);

      });
```

And after run i have:
`PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /vagrant/crm/terminal/api/vendor/crysalead/kahlan/src/plugin/Call.php on line 79`

**Comment by jails** [comment]
You use case is a bit uncommon since it's a mix of an integration test (since you wan't the real save feature) & some unit test since you wan't to stub it too. And the fact that you are using Phalcon models makes it more difficult since you must have the layer patcher configured for `Phalcon\Mvc\Model` since it's not some PHP file. So the inheritance is something like Stub->Layer->Model. So you will need to call up the grand parent directly so instead of `parent::save($data, $whitelist);` using `\Phalcon\Mvc\Model::save($data, $whitelist);` should solve this infinite loop issue.

**Comment by m1ome** [comment]
Thank for a help!
