### ISSUE TITLE
Matcher `->toContainKey()`

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#62]
It would be nice for readability to have a matcher `->toContainKey()` for arrays...like that:
```php
it('has required key', function () {
    expect(['name' => 'John', 'email' => 'john@example.com'])->toContainKey('name');
});
```
in addition to current possible ways:
```php
it('has required key', function () {
    expect(array_keys(['name' => 'John', 'email' => 'john@example.com']))->toContain('name');
});

it('has required key', function () {
    $arr = ['name' => 'John', 'email' => 'john@example.com'];
    expect(isset($arr['name']))->toBe(true);
});
```

**Comment by m1ome** [comment]
@tyranron implemented, let's see what @jails mind about it.

**Comment by tyranron** [comment]
@m1ome just forgot a phpdoc line:
```php
/**
* @method Matcher toContainKey(mixed $expected) passes if actual contains the expected key
*/
```
in `src/Matcher.php:10-28`

**Comment by jails** [comment]
Right now I only implemented the jasmine matchers and it was enough for me. But I'm not opposite to add some extra matchers if usefull. 

@m1ome maybe something like the following would be more generic:

```php
    public static function match($actual, $expected)
    {
        $expected = is_array($expected) ? $expected : [$expected];
        if (is_array($actual) || $actual instanceof ArrayAccess) {
            foreach ($expected as $key) {
                if(!isset($actual[$key])) {
                    return false;
                }
            }
            return true;
        } elseif ($actual instanceof Traversable) {
            foreach ($expected as $key) {
                foreach ($actual as $k => $v) {
                    if ($key === $k) {
                        continue 2;
                    }
                }
                return false;
            }
            return true;
        }
        return false;
    }
```

It would work for `Traversable` as well for `array` & `ArrayAccess` by using `isset()` directly (so no performance impact. And would also accept an array of keys like the following:

```php
it('has keys', function () {
    expect(['name' => 'John', 'email' => 'john@example.com'])->toContainKey(['name', 'email']);
});
```

**Comment by jails** [comment]
Or maybe the following syntax would be more interesting:

```php
it('has keys', function () {
    expect(['name' => 'John', 'email' => 'john@example.com'])->toContainKey('name', 'email');
});
```

**Comment by tyranron** [comment]
Hmm...I think all variants may be implemented.
`->toContainKey('name')` is just perfectly simple and clear way for single key check.
`->toContainKey('name', 'email')` is the most readable for multiple key check.
But if we know the exact set of keys only in runtime then `->toContainKey(['name', 'email'])` is the most comfortable.
For example:
```php
it('jonh info must have all required keys' , function () {
    $proto = ['name' => '', 'email' => null];
    $john = ['name' => 'John', 'email' => 'john@example.com'];
    expect($john)->toContainKey(array_keys($proto));
}); 
```

Also, with such behaviour extension of initial idea, name `->toContainKeys` is much intuitive and clear.

**Comment by m1ome** [comment]
@jails in your logick is better to do a do something like a symlink. `ToContainKey` and have a another `toContainKeys` that would do the trick with a array of keys provided.

**Comment by jails** [comment]
@tyranron like @m1ome said, we can indeed to the same trick as we did for [toBeA/toBeAn](https://github.com/crysalead/kahlan/blob/master/src/cli/Kahlan.php#L316-317) which are just aliases so we can use both syntax (for people who are attached to grammar) and have only one `ToContainKey`matcher which manage `('name')`, `('name', 'email')` and `(['name', 'email'])` notation.

**Comment by m1ome** [comment]
@jails i can fix the PR if you wish to!

**Comment by m1ome** [comment]
@jails :+1:

**Comment by m1ome** [comment]
@jails, review it. Traversable is just `abstract` class that provides us a view, that this `object` or `variable` support `foreach` method. No need do some trick for it.

**Comment by jails** [comment]
Sorry since it wasn't a bug or critical issue, I moved it down in my todo list.
So I'm closing it in flavor of #63

**Comment by tyranron** [comment]
Yay! Thank you! Love it!
