### ISSUE TITLE
Monkey patcher does not ignore control structure with `and` or `or` statements in some cases.

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#64]
The bug was found trying to stub methods of `PHPMailer` class of PHPMailer library.

When `new \PHPMailer()` was mentioned inside `describe` kahlan started to fall with error:
```
PHP Parse error:  syntax error, unexpected '$__KMONKEY__100' (T_VARIABLE) in /path/to/temp/projects/project/vendor/phpmailer/phpmailer/class.phpmailer.php on line 1347
```

If we look into patched code at that line (`1347`) we will see:
```php
if ('ssl' == $hostinfo[2] $__KMONKEY__100 ('' == $hostinfo[2] and 'ssl' == $this->SMTPSecure)) {
```
while original code is:
```php
if ('ssl' == $hostinfo[2] or ('' == $hostinfo[2] and 'ssl' == $this->SMTPSecure)) {
```

After changing `or` to `||` this place is patched ok. But have a similar issue on line `1576`:
```php
if ($qp_mode $__KMONKEY__117 ($__KMONKEY__118($word) > $length)) {
```
while original code is:
```php
if ($qp_mode and (strlen($word) > $length)) {
```

After changing `and` to `&&` at this place all file is patched ok and tests run normally.

I seems that issue appears when `and` and `or` statements are used together with parentheses.

Version of kahlan: `dev-master` (`cd04a55b27df999ede3110dffbeb9a6f9561869f`)
Version of PHPMailer: `v5.2.10` (`07005ecbb80d11ec8c0f067bb37e8909cc7fcbb7`)

**Comment by m1ome** [comment]
@jails pushed a PR, related to this bug.

**Comment by jails** [comment]
Thanks guys, fixed in https://github.com/crysalead/kahlan/commit/9a25da5947e3ca469b008e44b09fb7e872ee715e

**Comment by tyranron** [comment]
@jails thank you for fast reaction too.
Btw, can you update master branch?

**Comment by jails** [comment]
Yup I'll make a new release soon.
