### ISSUE TITLE
Matcher ->toContain() for strings

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#67]
Is it possible to implement version of `->toContain()` matcher for strings?
In same way as we have:
```php
it("passes if $actual has the correct length", function() {
    expect('Hello World!')->toHaveLength(12);
    expect(['a', 'b', 'c'])->toHaveLength(3);
});
```
It seems to be nice for redability to have something like that:
```php
it("passes if $actual contain $expected", function() {
    expect([1, 2, 3])->toContain(3);
    expect('Hello World!')->toContain('World');
});
```

**Comment by jails** [comment]
Should be fixed in https://github.com/crysalead/kahlan/commit/bf6d73e653ac98a880331c5c9cb6ad8ef51ba6b4, some parameters wasn't in the right order for an unknown reason.
