### ISSUE TITLE
Matcher ->toBeAn() as a copy of ->toBeA()

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#68]
Is it possible to implement matcher `->toBeAn()` as a copy of `->toBeA()` in the same way as we have `->toContainKey()` and `->toContainKeys()`?

Just for situations like:
```php
expect($some)->toBeAn('int');
expect($some)->toBeAn('array');
```

Grammar nazi doesn't let me sleep well.

**Comment by jails** [comment]
Afaik it's already the case: https://github.com/crysalead/kahlan/blob/master/src/cli/Kahlan.php#L316-317 no ?

**Comment by tyranron** [comment]
Yeap, that's it. So I was misinformed with static analysis of IDE.
Please, add required phpdoc line to `src/Matcher.php` .

**Comment by jails** [comment]
Fixed in https://github.com/crysalead/kahlan/commit/2009cd65a5fc8b980bcb8ac136f11edaa5665eaa

**Comment by m1ome** [comment]
Oooops, forgot to make a PR :sob:

**Comment by jails** [comment]
Haha, didn't even notice.
