### ISSUE TITLE
Strange behaviour of coverage for arrays definitions

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#69]
I have one method with 100% coverage in specs, however Kahlan coverage tool says no:
![no](https://habrastorage.org/files/ebd/b81/11f/ebdb8111f6ab4ca1bfb7f567daaea034.png)

But, if I remove last comma in array definition, it's OK:
![yes](https://habrastorage.org/files/d44/36e/90c/d4436e90ced4438594f8fd047fa99bb1.png)

But I cannot reproduce this issue in other methods:
![other](https://habrastorage.org/files/efc/0f5/de8/efc0f5de85e94cbfb7afaa63c61b30cd.png)

Version of Kahlan: 1.1.5 (d78b421d480e4549e613db5358d979f683028aea)

**Comment by jails** [comment]
It's a well know issue but unfortunately it's not something I can fix.
The main problem is Kahlan is based on xdebug which is based on the Zend engine which provide "buggy" code coverage results.
I tried to minimize the impact of issues like http://bugs.xdebug.org/view.php?id=1019 and similar issues but at some point when coverable lines are not marked up as covered Kahlan can't help.
So Kahlan gives more accurate coverage result in general, but still fail when xdebug go crazy.

**Comment by m1ome** [comment]
@tyranron to avoid something like this:
![](https://camo.githubusercontent.com/d43ee5f0811654aee1382485e4279cc48bad4511/68747470733a2f2f686162726173746f726167652e6f72672f66696c65732f6566632f3066352f6465382f65666330663564653835653934636266623761666161363363363162333063642e706e67)

Just don't use last comma.

**Comment by tyranron** [comment]
@jails, thanks for explanation.

@m1ome, however, using last comma in such cases is mandatory according to my company code format standards. But, I can live with that =)
