### ISSUE TITLE
JIT and control structures with `AND` or `OR` cases

### ISSUE THREAD

**Issue by tyranron** [crysalead/kahlan#71]
Sorry for annoying, but here I am again.

Issue is totally similar to #64. The only difference is that keywords are in upper case:

```php
if(($this->FontFamily == $family) AND ($this->FontStyle == $style) AND ($this->FontSizePt == $size) && !$forcewrite) {
	return $family;
}
```
is transformed to
```php
if(($this->FontFamily == $family) $__KMONKEY__1174 ($this->FontStyle == $style) $__KMONKEY__1174 ($this->FontSizePt == $size) && !$forcewrite) {
	return $family;
}
```

Same mPDF library.

Version of Kahlan: 1.1.6 (6f28e2471bda6a95b24c6da28c30a5eeba2a4d17)
Version of mPDF: v6.0.0 (a15743d030ce3b5b7be36c6e83f76589b27c3f2c)

**Comment by jails** [comment]
Ah yeah indeed looks like it's the same issue.
I fixed it again in https://github.com/crysalead/kahlan/commit/e11d606f1822321afcdd26b4da10195f078e06b2
