### ISSUE TITLE
Stub Help

### ISSUE THREAD

**Issue by KylePalko** [crysalead/kahlan#72]
I'm having trouble getting stubs to work. I've had them working in other projects in the past. Here is a test spec I created:

```<?php

use kahlan\plugin\Stub;

class MyClass {
    public function myMethod() {
        return 1;
    }
}

describe("Example", function() {

    it("stubs a method", function() {
        $instance = new MyClass();
        Stub::on($instance)->method('myMethod')->andReturn('Good Morning World!');
        expect($instance->myMethod())->toBe('Good Morning World!');
    });

    it("passes if true === true", function() {
        expect(true)->toBe(true);
    });

    it("passes if false !== true", function() {
        expect(false)->not->toBe(true);
    });
});
```

The integer 1 is still being returned despite the fact that I'm stubbing the method right before. I'm on version 1.1.8. The stub test is failing, but the others are passing. There are no errors. This is what Kahlan returns:

```
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The Unit/BDD PHP Test Framework for Freedom, Truth, and Justice.

Working Directory: /Users/kpalko/PhpstormProjects/ee-intl

Example
  ✘ it stubs a method
    expect->toBe() failed in `/spec/exporter/Csv/Test_Spec.php` line 16
    
    actual:
      (integer) 1
    expected:
      (string) "Good Morning World!"
    
  ✔ it passes if true === true
  ✔ it passes if false !== true


Executed 2 of 3 FAIL (FAILURE: 1) in 0.025 seconds
```

I'm sure I'm missing something silly. Any help would be greatly appreciated!

**Comment by jails** [comment]
As stated in the documentation: "code in *Spec.php files are not intercepted and patched". Which means `MyClass::myMethod()` can't be stubbed until loaded through Composer.

To sum up all the code present in *Spec.php files are not intercepted and therefore not patchable.

**Comment by KylePalko** [comment]
How would you recommend organizing your Stubs? Thanks for your quick reply by the way.

**Comment by jails** [comment]
Stubs doesn't need to be organized since your can create them dynamically using:
```php
$stub = Sub::create();
Stub::on($stub)->method('myMethod')->andReturn('Good Morning World!');
$stub->myMethod();
```
And you can also create some dynamic one base on existing classes:
```php
$stub = Sub::create(['extends' => 'MyClass']);
Stub::on($stub)->method('myMethod')->andReturn('Good Morning World!');
$stub->myMethod();
```

But if you need some specific mock instances, I would make sure I can autoload them from my `spec` directory.

So I would first configure my composer correctly with:

```php
"autoload": {
   "psr-4": {
       "myproject\\": "src/",
       "myproject\\spec\\": "spec/"
   }
}
```

And then make sure to set namespaces for all my specs so I do something like `use myproject\spec\mock\MyMock;`

I created a [sample repo](https://github.com/jails/temp/commit/0f6c9585aab5b26c3ca689f41d2eb40da126fd04), would probably make more sense.

**Comment by KylePalko** [comment]
Awesome man! Thanks. That's really neat. I didn't realize I should be using Stub::create. That all works!

**Comment by jails** [comment]
You're welcome !
