### ISSUE TITLE
Code coverage ignore annotations or similar?

### ISSUE THREAD

**Issue by gavD** [crysalead/kahlan#74]
Just wondering, is there a way to tell Kahlan's code coverage to ignore a region of untestable code? Something like `@codeCoverageIgnore` in PHPUnit.

**Comment by m1ome** [comment]
Could you please provide a sample of untestable code?

**Comment by gavD** [comment]
I'm referring to things like specific `curl` calls, touching the real file system, etc.

Here's an example:

```php
<?php
class Getter {
  function getStuff() {
    return curl ('some url');
  }

  public function processStuff() {
    $stuff = $this->getStuff();
    foreach($stuff as $thing) {
      // do something...
    }
  }
}
```

Generally, I would stub out the `getStuff()` method. Hmm, thinking about it, I suppose I can test around it using stubs and monkey patching and actually monkey patch `curl` itself, but it seems like it would be helpful to simply mark the getStuff method as explicitly untested.

**Comment by m1ome** [comment]
If you stub (Monkey patch) `curl` function it would be much more "right way":
* You will test this `return curl();` string for running
* You will control test, that can be done after, tests that will use this `getStuff` function

Full code coverage is a one of many points to think that application at least don't drop with fatal.

**Comment by jails** [comment]
Unfortunately there's no such feature. Until now I was always able to find a workaround with some monkey patching, but I must admit this feature would save some time especially when xdebug provides some buggy coverage result.
