### ISSUE TITLE
Version number out of date

### ISSUE THREAD

**Issue by gavD** [crysalead/kahlan#75]
I am using Kahlan 1.1.8 but it reports as 1.1.3

The cause is this line, which is hard coded:

https://github.com/crysalead/kahlan/blob/master/src/cli/Kahlan.php#L35

Thanks,
- Gavin

**Comment by m1ome** [comment]
@jails, i think we must do some composer magic for not hardcoding version into config file. 
@gavD, good catch :+1:

**Comment by jails** [comment]
I'm not sure composer can be of any help here.
I think this is going to pissing me off for a while !

Btw, thanks for the head up @gavD !

**Comment by jails** [comment]
Fixed in https://github.com/crysalead/kahlan/commit/8fad06d63a5d7083822041a35a45b98e9b9ce29c
