### ISSUE TITLE
Running on windows fails

### ISSUE THREAD

**Issue by crissi** [crysalead/kahlan#84]
I am running WIndows 10. Release: 1.2.0 - Have not tried other branches.

Warning: mkdir(): Invalid argument in C:\Users\MyUserName\AppData\Roaming\Composer\vendor\crysalead\jit\src\Interceptor.php on line 436

Warning: file_put_contents(C:\Users\MyUserName\AppData\Local\Temp\kahlan\C:\Users\MyUserName\AppData\Roaming\Composer\vendor/crysalead/dir/src\Dir.php): failed to open stream: Invalid argument in C:\Users\MyUserName\AppData\Roaming\Composer\vendor\crysalead\jit\src\Interceptor.php on line 438

Warning: touch(): Unable to create file C:\Users\MyUserName\AppData\Local\Temp\kahlan\C:\Users\MyUserName\AppData\Roaming\Composer\vendor/crysalead/dir/src\Dir.php because Invalid argument in C:\Users\MyUserName\AppData\Roaming\Composer\vendor\crysalead\jit\src\Interceptor.php on line 440

Warning: require(C:\Users\MyUserName\AppData\Local\Temp\kahlan\C:\Users\MyUserName\AppData\Roaming\Composer\vendor/crysalead/dir/src\Dir.php): failed to open stream: Invalid argument in C:\Users\MyUserName\AppData\Roaming\Composer\vendor\crysalead\jit\src\Interceptor.php on line 401

Fatal error: require(): Failed opening required 'C:\Users\MyUserName\AppData\Local\Temp\kahlan\C:\Users\MyUserName\AppData\Roaming\Composer\vendor/crysalead/dir/src\Dir.php' (include_path='C:\Users\MyUserName\AppData\Roaming\Composer\vendor/phpunit/php-text-template;C:\Users\MyUserName\AppData\Roaming\Composer\vendor/phpunit/php-timer;C:\Users\MyUserName\AppData\Roaming\Composer\vendor/phpunit/php-file-iterator;.;C:\php\pear') in C:\Users\MyUserName\AppData\Roaming\Composer\vendor\crysalead\jit\src\Interceptor.php on line 401

**Comment by jails** [comment]
Thanks for the report.
Should be solved in the last version.
