### ISSUE TITLE
before() can't run in another spec for specifying object

### ISSUE THREAD

**Issue by samsonasik** [crysalead/kahlan#90]
For example, I have class:

```php
class Foo
{
    public function __construct(Dependency $d)
    {
        $this->d = $d;
    }
}
```

and the `Dependency` class:

```php
class Dependency
{
       public function __construct($a, $b, $c) {}
}
```

I created `FooSpec` for `Foo` class:
```php
// FooSpec.php
describe('Foo', function() {

    before(function() {
        $this->dependency = Stub::create(['class' => Dependency::class]);
        $this->foo = new Foo($this->dependency);
    });

});
```
and for `DependencySpec` for `Dependency` class:
```php
describe('Dependency', function() {

    before(function() {
        $this->dependency = new Dependency(1, 2, 3);
    });

});
```

I got error:

```bash
Executed 0 of 1 FAIL (EXCEPTION: 1) in 0.016 seconds
```

**Comment by samsonasik** [comment]
description above updated.

**Comment by samsonasik** [comment]
the error when I use `--reporter=bar` : 
```
`E_WARNING` Missing argument 1 for App\\Dependency::__construct(),
```

**Comment by samsonasik** [comment]
the `new Dependency(1, 2, 3)` still not work even I use it in `it()` function, seems `Stub::create` in another spec replace it and make the class one and the only?

**Comment by jails** [comment]
In PHP class redefinition is not possible even with Kahlan.
When you write:

```php
$this->dependency = Stub::create(['class' => Dependency::class]);
```

It means that you are creating a stub called `Dependency::class`. Once created the real `Dependency::class` class won't ever be autoloaded and this "fake" class will be used everywhere instead.

I would recommand to create your stubs using `'extends'` instead of class `'class'`

```php
$this->dependency = Stub::create(['extends' => Dependency::class]);
```

So the real `Dependency::class` class will be autoloaded as expected.

**Comment by samsonasik** [comment]
I still get same error, I tried:

```php
            $this->dependency = Stub::create([
                'extends' => Dependency::class,
                'params' => [1]
            ]);
```

**Comment by jails** [comment]
Can you publish your whole exemple as a github repo so I can play with it a bit ?

**Comment by samsonasik** [comment]
oh, yeah, it's working now with uses : 
```
$this->dependency = Stub::create([
            'extends' => Dependency::class,
            'params' => [1]
        ]);
```
in both spec ( `DependencySpec` and `FooSpec` ), but can't we use real `Dependency` class then ?

**Comment by samsonasik** [comment]
btw, I published the repo in https://github.com/sitrunlab/learn-kahlan

**Comment by jails** [comment]
sure it should work.

**Comment by samsonasik** [comment]
hmm., I tried real `new Dependency(1)` call in `DependencySpec` and got the `Missing argument 1` error

**Comment by jails** [comment]
Weird, just cloned your repo and used `$this->object = new Dependency(1);` in `DependencySpec` and it's working.

**Comment by jails** [comment]
Does the error message gives you the file name location where the error occurred ?

**Comment by samsonasik** [comment]
I got the error:
```bash
✘ Foo
  an uncaught exception has been thrown in `/private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/src/Dependency.php` line 7
  
  message:`kahlan\PhpErrorException` Code(0) with message "`E_WARNING` Missing argument 1 for App\\Dependency::__construct(), called in /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/plugin/Stub.php on line 196 and defined"
  
    [NA] - /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/learn-kahlan/src/Dependency.php, line  to 7
    App\Dependency::__construct() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/plugin/Stub.php, line 196
    kahlan\plugin\Stub::create() - /Users/samsonasik/www/learn-kahlan/spec/FooSpec.php, line 17
    kahlan\Suite::runCallbacks() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/Suite.php, line 326
    kahlan\Suite::_suiteStart() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/Suite.php, line 299
    kahlan\Suite::process() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/Suite.php, line 304
    kahlan\Suite::process() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/Suite.php, line 417
    kahlan\Suite::run() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/cli/Kahlan.php, line 540
    filter\Filter::on() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/cli/Kahlan.php, line 541
    kahlan\cli\Kahlan::_run() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/cli/Kahlan.php, line 361
    filter\Filter::on() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/src/cli/Kahlan.php, line 369
    kahlan\cli\Kahlan::run() - /Users/samsonasik/www/learn-kahlan/vendor/crysalead/kahlan/bin/kahlan, line 44
```

Actually, I don't want to pass '`params' => [1]` in FooSpec::before:
```php
describe('Foo', function() {

    before(function() {
        $this->dependency = Stub::create([
            'class' => Dependency::class,
            //'params' => [1] 
        ]);
        $this->object = new Foo($this->dependency);
    });

});
```

**Comment by samsonasik** [comment]
as `$this->dependency` in `FooSpec` is not a real object, so I don't want to build the `$this->dependency`with its constructor parameters

**Comment by samsonasik** [comment]
this commit https://github.com/sitrunlab/learn-kahlan/commit/ff62e109937dcb474623eb586d629b97f2870352 make the failure tests

**Comment by jails** [comment]
To create a fake object you can use `Stub::create()` without parameter, but in your case you setted up the following typehint `__construct(Dependency $d)` in the `Foo` class. So you need to create a stub which extends `Dependency` to make it passes the typehint.

Once your stubs extends `Dependency` it'll inherits its constructor, so you can't juste ignore `__construct` the required parameter.

So either you can change the `Dependency` constructor by `public function __construct($a = null)`, so it can accept no parameter.

Or you can create a stub which override the construct method at the stub level:
```php
$this->dependency = Stub::create([
    'extends' => Dependency::class,
    'methods'  => ['__construct']
]);
```
Btw [I don't use typehints personnaly](http://radify.io/blog/type-hinting-in-php-good-or-bad-practice/)

**Comment by samsonasik** [comment]
thank you ;). The override construct method make it works. I'm closing it ;)

**Comment by samsonasik** [comment]
the code comment in `Stub::create()` need update about 'methods' options, I will create PR for that

**Comment by samsonasik** [comment]
I created PR https://github.com/crysalead/kahlan/pull/91 for 'methods' key options.

**Comment by jails** [comment]
Personnaly [I don't use typehint](http://radify.io/blog/type-hinting-in-php-good-or-bad-practice/) which simplify a bit stubs creation by the way.

**Comment by samsonasik** [comment]
ok, but that's 'methods' key of options is undocumented in `create()` method, so i created PR #91
